import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ProvidersWrapper from '@/components/ProvidersWrapper';
import Navbar from '@/components/Navbar';
import { clsx } from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-stone-100 text-stone-900')}>
        <ProvidersWrapper>
          <header className="sticky top-10">
            <Navbar />
          </header>
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
